using System;

namespace XForms.Enums
{
    public enum AppServices
    {
        //STOCKADJUSTMENT= 10,
        //ORDER = 11,
        //RECEPTIONS = 12,
        //MJ_CMDPDA = 1006,
        //_Retourfournisseur = 13,
        //MJ_POSSTOCK = 1005,
        INVENTORIES = 14,
        //CYCLECOUNT = 15,
        _Prix = 16,
        //_Receptionexterne = 17,
        //PARAMETRESARTICLE = 18,
        //INVSANSINIT = 19,
        INFOGENARTICLE = 20,
        //DELAIRETRAIT = 21,
        DEMANDEETI = 22,
        //CONTROLERUPTURE = 24,
        //CONTROLESURSTOCK = 25,
        //GestionduStock = 27,
        //CESSINTRAYON = 30,
        //_Assortiments = 33,
        //TRANSFERSANSREQUETE = 34,
        //_Article = 35,
        //_Modedeconnecte = 38,
        //MOTDEPASSE = 51,
        //PRERECEPTIONS = 55,
        //MJ_CONTROLERUPTURE = 900,
        //_Venteassistée = 910,
        //_Reserve = 950,
        _ARRIVAGESMAGASINS = 1000,
        //MJ_RECEPTIONS = 1003,
        //MJIMPRIMPRIX = 1004,
        //NOUVPROD = 40,
        //PRODSORT = 41,
        //SUPPLIERRETURNS = 42,
        CTRLPRIX = 36,
        //CONTROLPRIX = 37,
        OPFRAIS = 52,
        //RECEPTIONEXTERN = 610,
        //RECEPTIONEXTSUPP = 620,
        //CONTROLESELONCRITERES = 123,
        //PLANNING = 124,
        //SAISIECASSE = 31,
        //_Assortcommandables = 1,
        //BALISAGE = 351,
        //BALISAGESANSLISTE = 352,
        //DEMANDEETIDC = 39,
        //SAISIECASSEDC = 43,
        //BALISAGEDC = 44,
        //PLANNINGDC = 45,
        //CONTROLERUPTUREDC = 46,
        //CONTROLESURSTOCKDC = 47,
        //CONTROLERUPTURELISTE = 48,
        //CONTROLESURSTOCKLISTE = 49,
        //INVENTORIESDC = 53,
        //CYCLECOUNTDC = 54,
        //SUIVIARTICLEOSRUPTURE = 502,
        //SUIVIARTICLEOSSURSTOCK = 503,
        //MJ_CREATION_BDV = 911,
        //MJ_RSV_CREATION_PALETTE = 501,
        //MJ_RSV_MODIFICATION_PALETTE = 952,
        //MJ_RSV_STOCKER_PALETTE = 953,
        //MJ_RSV_DESCENTE_PALETTE = 954,
        //MJ_RSV_INFO_ARTICLE = 955,
        //MJ_CREATION_ARRIVAGE = 1001,
        //MJ_MODIFICATION_ARRIVAGE = 1002,

        Demarque = 1007,
        Miseajour = 18,
        Reserve = 950,
        MJ_CMDPDA = 1006,
        DemarqueValidation = 1012,
        InnovTouch = 1008,
    }
}